# Generated by Django 5.1.7 on 2025-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'دستاورد',
                'verbose_name_plural': 'دستاوردها',
            },
        ),
    ]
