# Generated by Django 5.1.7 on 2025-04-01 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='image',
            field=models.ImageField(blank=True, help_text='فقط فایل\u200cهای WebP با ابعاد 700x900 پیکسل قابل قبول هستند', null=True, upload_to='achievements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])], verbose_name='تصویر'),
        ),
    ]
