# Generated by Django 5.1.7 on 2025-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=128, verbose_name='رمز عبور')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مدیر')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر سیستم')),
            ],
        ),
    ]
