# Generated by Django 5.1.7 on 2025-04-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='email',
            field=models.EmailField(blank=True, default='info@ttoqom.ir', max_length=254, null=True),
        ),
    ]
