# Generated by Django 5.1.7 on 2025-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'زیرخبر',
                'verbose_name_plural': 'زیرخبرها',
            },
        ),
    ]
